//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectColectiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervare
    {
        public int Id { get; set; }
        public int IdLoc { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public int IdMasina { get; set; }
    
        public virtual LocParcare LocParcare { get; set; }
        public virtual Masina Masina { get; set; }
    }
}
